name: "SmartBanking"
description: "Smart Banking by Hibiscus"
version: "0.0.1"
slug: "smart_banking"
init: false
arch:
  - armhf
ports:
  8888/tcp: 8888
options:
  database_url: ""
  database_username: ""
  database_password: ""
  hibiscus_password: ""
schema:
  hibiscus_password: password
  database_url: str
  database_username: str
  database_password: password
